[package]
name = "transaction-emitter"
version = "0.0.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos transaction emitter for testing"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = { version = "1.0.57", features = ["backtrace"] }
clap = "3.1.17"
futures = "0.3.21"
itertools = "0.10.3"
rand = "0.7.3"
rand_core = "0.5.1"
termion = "1.5.6"
tokio = { version = "1.18.2", features = ["full"] }
tokio-metrics = { version = "0.1.0", default-features = false, features = ["rt"] }

aptos-logger = { path = "../../crates/aptos-logger" }
aptos-sdk = { path = "../../sdk" }

transaction-emitter-lib = { path = "../../crates/transaction-emitter-lib" }
